### ISSUE TITLE
Recommendation: Rename NuGet Package

### ISSUE THREAD

**Issue by jamesmontemagno** [kphillpotts/Xamarin.Plugins#1]
Hey there! Awesome plugin :)

I wanted to see if you were able to update your NuGets name to "Lamp Plugin for Xamarin and Windows" to align with all of the other plugins out there. Helps with SEO and people will know it will work with WP/WS apps as well.

Let me know, and thanks for this plugin!

james

**Comment by kphillpotts** [comment]
Renamed the existing nuget package to "Lamp Plugin for Xamarin and Windows" from the Nuget site.  Not sure if this is a kosher way to do it, but seems fine.  I'll be publishing an update shortly that has lamp brightness property as well, so I'll make sure it's updated then too.
